In [ ]:
import numpy as np
from scipy import linalg as SLA
import math as m

In [ ]:
def TwoEquations(x,xp):
    v1=np.array([0,0,0,0,  -xp[2]*x[0],-xp[2]*x[1],-xp[2]*x[2],-xp[2]*x[3],   xp[1]*x[0],xp[1]*x[1],xp[1]*x[2],xp[1]*x[3]      ])
    v2=np.array([xp[2]*x[0],xp[2]*x[1],xp[2]*x[2],xp[2]*x[3],0,0,0,0, -xp[0]*x[0],-xp[0]*x[1],-xp[0]*x[2],-xp[0]*x[3]])
    return v1,v2
def CameraDLP(points_original,points_images):
    n=len(points_original)
    if(n!=len(points_images)):
      print("Razlicit broj tacaka u originalu i slici")
    e1,e2=TwoEquations(points_original[0],points_images[0])
    A = np.vstack((e1,e2))
    for i in range(1,n):
        e1,e2=TwoEquations(points_original[i],points_images[i])
        A = np.vstack([A, e1])
        A = np.vstack([A, e2])
    _, _, V = np.linalg.svd(A)
    P = V[-1, :] 
    P=P.reshape(3,4)
    return P
n=2; #N = 2
M1=(460,280,250,1)
M2=(50,380,350,1)
M3=(470,500,100,1)
M4=(380,630,50*n,1)
#M4=(380,630,0,1)
M5=(30*n,290,0,1)
#M5=(240,290,0,1)
M6=(580,0,130,1)

M1p=(288,251,1)
M2p=(79,510,1)
M3p=(470,440,1)
M4p=(520,590,1)
M5p=(365,388,1)
M6p=(365,20,1)
points_original=[M1,M2,M3,M4,M5,M6]
points_images=[M1p,M2p,M3p,M4p,M5p,M6p]
matrica=CameraDLP(points_original,points_images)
matrica=matrica/matrica[0,0]
print("Matrica T")
with np.printoptions(precision=10, suppress=True):
  print(matrica)


Matrica T
[[    1.               0.212637819     10.2571641027 -4173.8220561728]
 [    5.0457732123    -2.836051882      5.2836650151 -3774.5706466265]
 [    0.0082469732     0.0048303107     0.0154891901   -13.0012708653]]


In [ ]:
def IzracunajC(T):
  matr1=np.array([T[:,1],T[:,2],T[:,3]])
  det1=np.linalg.det(matr1)
  matr2=np.array([T[:,0],T[:,2],T[:,3]])
  det2=-np.linalg.det(matr2)
  matr3=np.array([T[:,0],T[:,1],T[:,3]])
  det3=np.linalg.det(matr3)
  matr4=np.array([T[:,0],T[:,1],T[:,2]])
  det4=-np.linalg.det(matr4)
  det1=det1/det4
  det2=det2/det4
  det3=det3/det4
  return det1,det2,det3
def ParametriKamere(T):
  c1,c2,c3=IzracunajC(T) 
  T0=[T[:,0],T[:,1],T[:,2] ]
  if np.linalg.det(T0)<0:
    T0=T0*(-1) 
  Tinverz=np.linalg.inv(T0).T
  q, r = SLA.qr(Tinverz)
  if r[0,0]<0:
    r[0,0]=-r[0,0]
    r[0,1]=-r[0,1]
    r[0,2]=-r[0,2]
    q[0,0]=-q[0,0]
    q[1,0]=-q[1,0]
    q[2,0]=-q[2,0]
  if r[1,1]<0:
    r[1,1]=-r[1,1]
    r[1,0]=-r[1,0]
    r[1,2]=-r[1,2]
    q[1,1]=-q[1,1]
    q[1,1]=-q[1,1]
    q[2,1]=-q[2,1]
  if r[2,2]<0:
    r[2,0]=-r[2,0]
    r[2,1]=-r[2,1]
    r[2,2]=-r[2,2]
    q[0,2]=-q[0,2]
    q[1,2]=-q[1,2]
    q[2,2]=-q[2,2]
  k=np.linalg.inv(r)
  if k[2,2]!=1:
    k=k/k[2,2]
  a=np.matrix.transpose(q)
  return a,k,c1,c2,c3
n=2
T=np.array([[5,-1-2*n,3,18-3*n],[0,-1,5,21],[0,-1,0,1]])
#T=matrica
a,k,c1,c2,c3=ParametriKamere(T)
print("Matrica K:")
with np.printoptions(precision=10, suppress=True):
  print(k)
print("Matrica A")
print(np.round(a,6))
c=np.array([c1,c2,c3])
print("Pozicija kamere C: ")
print(np.round(c,3))

Matrica K:
[[5. 3. 5.]
 [0. 5. 1.]
 [0. 0. 1.]]
Matrica A
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]
Pozicija kamere C: 
[ 1.  1. -4.]


In [ ]:
T=np.array([[5,-5,3,12],[0,-1,5,21],[0,-1,0,1]])
#T=np.array([[-2,3,0,7],[-3,0,3,-6],[1,0,0,-2]])
#T=np.array([[-5,2,0,1],[3,0,2,-9],[1,0,0,-1]])
#T=np.array([[5,-23,3,-15],[0,-1,5,21],[0,-1,0,1]])



def IzracunajC(T):
  print("T")
  print(T)
  matr1=np.array([T[:,1],T[:,2],T[:,3]])
  det1=int(np.round(np.linalg.det(matr1)))
  matr2=np.array([T[:,0],T[:,2],T[:,3]])
  det2=int(np.round(-np.linalg.det(matr2)))
  matr3=np.array([T[:,0],T[:,1],T[:,3]])
  det3=int(np.round(np.linalg.det(matr3)))
  matr4=np.array([T[:,0],T[:,1],T[:,2]])
  det4=int(np.round(-np.linalg.det(matr4)))
  print("DETTTTTTTTS")
  print(det1,det2,det3,det4)
  #nzd1=m.gcd(det1,det2)
  #nzd2=m.gcd(nzd1,det3)
  #nzd=m.gcd(nzd2,det4)
  #det1=det1/nzd
  #det2=det2/nzd
  #det3=det3/nzd
  #det4=det4/nzd
  det1=det1/det4
  det2=det2/det4
  det3=det3/det4
  return det1,det2,det3
def ParametriKamere(T):
  c1,c2,c3=IzracunajC(T) 
  T0=[T[:,0],T[:,1],T[:,2] ]
  if np.linalg.det(T0)<0:
    T0=T0*(-1) 
  Tinverz=np.linalg.inv(T0).T
  q, r = SLA.qr(Tinverz)
  if r[0,0]<0:
    r[0,0]=-r[0,0]
    r[0,1]=-r[0,1]
    r[0,2]=-r[0,2]
    q[0,0]=-q[0,0]
    q[1,0]=-q[1,0]
    q[2,0]=-q[2,0]
  if r[1,1]<0:
    r[1,1]=-r[1,1]
    r[1,0]=-r[1,0]
    r[1,2]=-r[1,2]
    q[1,1]=-q[1,1]
    q[1,1]=-q[1,1]
    q[2,1]=-q[2,1]
  if r[2,2]<0:
    r[2,0]=-r[2,0]
    r[2,1]=-r[2,1]
    r[2,2]=-r[2,2]
    q[0,2]=-q[0,2]
    q[1,2]=-q[1,2]
    q[2,2]=-q[2,2]
  k=np.linalg.inv(r)
  if k[2,2]!=1:
    k=k/k[2,2]
  a=np.matrix.transpose(q)
  return a,k,c1,c2,c3

T=matrica
#n=2  
#T=np.array([[1,5,7,-2],[3,0,2,3],[4,-1,0,1]])
#T=np.array([[5,-1-2*n,3,18-3*n],[0,-1,5,21],[0,-1,0,1]])
#T=np.array([[5,-23,3,-15],[0,-1,5,21],[0,-1,0,1]])
a,k,c1,c2,c3=ParametriKamere(T)
print("Matrica K:")
print(k)
print("Matrica A")
print(a)
c=np.array([c1,c2,c3])
print("Pozicija kamere C: ")
print(c)

T
[[ 1.77699489e-04  3.77856318e-05  1.82269282e-03 -7.41686047e-01]
 [ 8.96631322e-04 -5.03964970e-04  9.38904574e-04 -6.70739275e-01]
 [ 1.46548293e-06  8.58343738e-07  2.75242116e-06 -2.31031919e-03]]
DETTTTTTTTS
0 0 0 0


ZeroDivisionError: ignored